name: Setup Typst CLI
description: 📑 Install Typst for use in GitHub Actions

branding:
  icon: terminal
  color: white

inputs:
  typst-token:
    default: ${{ github.server_url == 'https://github.com' && github.token || '' }}
  typst-version:
    default: latest

outputs:
  typst-version: {}
  cache-hit: {}

runs:
  using: node20
  main: dist/main.js
