name: Setup Typst
description: 📑 Install Typst and add it to the PATH with package management

branding:
  icon: terminal
  color: white

inputs:
  typst-version:
    description: "Version range or exact version of Typst to use, using SemVer's version range syntax. Uses the latest version if unset."
    default: latest
  allow-prereleases:
    description: "When 'true', a version range including 'latest' passed to 'typst-version' input will match prerelease versions."
    default: false
  cache-dependency-path:
    description: "Used to specify the path to a Typst file containing lines of 'import' keyword."
    required: false
  zip-packages:
    description: "Used to specify the path to a JSON file containing names and ZIP archive URLs of packages."
    required: false
  local-packages:
    description: "[Deprecated] Used to specify the path to a JSON file containing names and ZIP archive URLs of packages. Use 'zip-packages' instead."
    required: false
  cache-local-packages:
    description: "When 'true', local packages set by 'zip-packages' will be cached independently of '@preview' packages."
    default: false
  token:
    description: "The token used to authenticate when fetching Typst distributions from typst/typst. When running this action on github.com, the default value is sufficient. When running on GHES, you can pass a personal access token for github.com if you are experiencing rate limiting."
    default: ${{ github.server_url == 'https://github.com' && github.token || '' }}

outputs:
  typst-version:
    description: "The installed Typst version. Useful when given a version range as input."
  cache-hit:
    description: "A boolean value to indicate a cache entry was found."

runs:
  using: node20
  main: dist/main/index.js
