name: Setup Typst
description: 📑 Install Typst for use in GitHub Actions

branding:
  icon: terminal
  color: white

inputs:
  typst-token:
    description: >
      The GitHub token to use when pulling versions from typst/typst. By default
      this should cover all cases. You shouldn't have to touch this setting.
    default:
      ${{ github.server_url == 'https://github.com' && github.token || '' }}
  typst-version:
    description: >
      The version of Typst to install. This can be an exact version like '0.10.0'
      or a semver range like '0.10' or '0.x'. You can also specify 'latest' to
      always use the latest version. The default is 'latest'.
    default: latest
  cache-dependency-path:
    description: >
      Used to specify the path to dependency file. Supports a Typst file with
      lines of 'import' keyword.
    required: false

outputs:
  typst-version:
    description: >
      The version of Typst that was installed. This will be something like
      '0.10.0' or similar.
  cache-hit:
    description: >
      Whether or not Typst was restored from the runner's cache or download anew.

runs:
  using: node20
  main: dist/main/index.js
