name: Setup Typst
author: yusancky
description: Setup Typst in GitHub Actions
inputs:
  token:
    description: The token used to authenticate when fetching Typst distributions. When running this action on github.com, the default value is sufficient. When running on GHES, you can pass a personal access token for github.com if you are experiencing rate limiting.
    default: ${{ github.server_url == 'https://github.com' && github.token || '' }}
  version:
    description: Exact version of Typst to use.
runs:
  using: composite
  steps:
    - name: Download release
      uses: robinraju/release-downloader@v1.7
      with:
        repository: "typst/typst"
        tag: ${{ inputs.version }}
        fileName: "typst-x86_64-pc-windows-msvc.zip"
        token: ${{ inputs.token }}
    - name: Unzip Typst
      run: 7z x typst-x86_64-pc-windows-msvc.zip -oc:\typst typst.exe -r
      shell: bash
    - name: Delete zip
      run: rm -f typst-x86_64-pc-windows-msvc.zip
      shell: bash
    - name: Add system path
      run: echo "c:\typst\typst-x86_64-pc-windows-msvc" >> $GITHUB_PATH
      shell: bash
branding:
  color: blue
  icon: download
