name: Setup Typst CLI

branding:
  color: white
  icon: download

inputs:
  typst-token:
    default: ${{ github.server_url == 'https://github.com' && github.token || '' }}
  typst-version:
    default: latest

runs:
  using: node20
  main: dist/main.js
