name: Setup Typst
author: yusancky
description: Setup Typst in GitHub Actions
inputs:
  token:
    description: The token used to authenticate when fetching Typst distributions. When running this action on github.com, the default value is sufficient. When running on GHES, you can pass a personal access token for github.com if you are experiencing rate limiting.
    default: ${{ github.server_url == 'https://github.com' && github.token || '' }}
  version:
    description: Exact version of Typst to use.
runs:
  using: composite
  steps:
    - name: Configure filenames (Linux)
      run: |
        echo "typst_zip_name=unknown-linux-gnu" >> $GITHUB_ENV
        echo "typst_zip_extend=tar.gz" >> $GITHUB_ENV
      shell: bash
      if: runner.os == 'Linux'
    - name: Configure filenames (Windows)
      run: |
        echo "typst_zip_name=pc-windows-msvc" >> $GITHUB_ENV
        echo "typst_zip_extend=zip" >> $GITHUB_ENV
      shell: bash
      if: runner.os == 'Windows'
    - name: Configure filenames (macOS)
      run: |
        echo "typst_zip_name=apple-darwin" >> $GITHUB_ENV
        echo "typst_zip_extend=tar.gz" >> $GITHUB_ENV
      shell: bash
      if: runner.os == 'macOS'
    - name: Download release
      uses: robinraju/release-downloader@v1.7
      with:
        repository: typst/typst
        tag: ${{ inputs.version }}
        fileName: ${{ format('typst-x86_64-{0}.{1}', env.typst_zip_name, env.typst_zip_extend) }}
        token: ${{ inputs.token }}
    - name: Unzip Typst (Linux)
      run: |
        sudo mkdir /typst
        ${{ format('sudo tar -xzf typst-x86_64-{0}.{1} typst -C /typst/', env.typst_zip_name, env.typst_zip_extend) }}
      shell: bash
    - name: Unzip Typst (Windows)
      run: ${{ format('7z x typst-x86_64-{0}.{1} -oc:\typst typst.exe -r', env.typst_zip_name, env.typst_zip_extend) }}
      shell: bash
      if: runner.os == 'Windows'
    - name: Unzip Typst (macOS)
      run: |
        sudo mkdir /typst
        ${{ format('sudo 7z x typst-x86_64-{0}.{1} -o/typst/ typst', env.typst_zip_name, env.typst_zip_extend) }}
      shell: bash
      if: runner.os == 'macOS'
    - name: Delete zip
      run: ${{ format('rm -f typst-x86_64-{0}.{1}', env.typst_zip_name, env.typst_zip_extend) }}
      shell: bash
    - name: Add system path (Linux, macOS)
      run: echo "/typst/" >> $GITHUB_PATH
      shell: bash
      if: runner.os == 'Linux' || runner.os == 'macOS'
    - name: Add system path (Windows)
      run: echo "c:\typst\typst-x86_64-pc-windows-msvc" >> $GITHUB_PATH
      shell: bash
      if: runner.os == 'Windows'
branding:
  color: blue
  icon: download
