name: Setup Typst
description: 📑 Install Typst for use in GitHub Actions

branding:
  icon: terminal
  color: white

inputs:
  typst-version:
    description: "Version range or exact version of Typst to use, using SemVer's version range syntax. Uses the latest version if unset."
    default: latest
  allow-prereleases:
    description: "When 'true', a version range including 'latest' passed to 'typst-version' input will match prerelease versions."
    default: false
  cache-dependency-path:
    description: "Used to specify the path to dependency file. Supports a Typst file with lines of 'import' keyword."
    required: false
  token:
    description: "The token used to authenticate when fetching Typst distributions from typst/typst. When running this action on github.com, the default value is sufficient. When running on GHES, you can pass a personal access token for github.com if you are experiencing rate limiting."
    default: ${{ github.server_url == 'https://github.com' && github.token || '' }}

outputs:
  typst-version:
    description: "The installed Typst version. Useful when given a version range as input."
  cache-hit:
    description: "A boolean value to indicate a cache entry was found."

runs:
  using: node20
  main: dist/main/index.js
