name: Setup Typst
description: 📑 Install Typst for use in GitHub Actions

branding:
  icon: terminal
  color: white

inputs:
  typst-token:
    description: >
      The GitHub token to use when pulling versions from typst/typst. By default
      this should cover all cases. You shouldn't have to touch this setting.
    default: ${{ github.server_url == 'https://github.com' && github.token || '' }}
  typst-version:
    description: >
      The version of Typst to install. This can be an exact version like
      '0.10.0' or a semver range like '0.10' or '0.x'. You can also specify
      'latest' to always use the latest version. The default is 'latest'.
    default: latest
  cache:
    description: Whether or not to cache any Typst packages installed during the workflow. Defaults to 'true'.
    default: true
  cache-dependency-path:
    description: This should be any '.typ' file that when changed you wish to invalidate previous Typst package caches. By default it's '**/*.typ'.
    default: "**/*.typ"

outputs:
  typst-version:
    description: >
      The version of 'typst' that was installed. This will be something like
      '0.10.0' or similar.
  cache-hit:
    description: >
      Whether or not Typst was restored from the runner's cache or download
      anew.

runs:
  using: node20
  main: dist/main.js
  post: dist/post.js
